baseURL = "https://ottawabaptist.ca/"
title = "Ottawa Baptist Association"
theme = "oba"
contentDir = "content"
languageCode = "en-us"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    disabled = false
    languageName = "EN"
    languageCode = "en-CA"
    title = "Ottawa Baptist Association"
    [languages.en.params]
      subtitle = ""
    weight = 10
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'About Us'
        url = '/en/about/'
        weight = 10
      [[languages.en.menus.main]]
        name = 'Churches'
        url = '/en/churches/'
        weight = 20

  [languages.fr]
    disabled = false
    languageName = "FR"
    languageCode = "fr-CA"
    title = "L' Association Baptiste D' Ottawa"
    [languages.fr.params]
      subtitle = ""
    weight = 20
    [languages.fr.menus]
      [[languages.fr.menus.main]]
        name = 'À propos de nous'
        url = '/fr/about/'
        weight = 10
      [[languages.fr.menus.main]]
        name = 'Églises'
        url = '/fr/churches/'
        weight = 20
